### ISSUE TITLE
Cannot generate uploader

### ISSUE THREAD

**Issue by cheunghy** [huacnlee/carrierwave-aliyun#17]
```
bundle exec rails generate uploader Image
/usr/local/lib/ruby/gems/2.2.0/gems/carrierwave-aliyun-0.3.3/lib/carrierwave/storage/aliyun.rb:3:in `require': cannot load such file -- digest/hmac (LoadError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/carrierwave-aliyun-0.3.3/lib/carrierwave/storage/aliyun.rb:3:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.2.0/gems/carrierwave-aliyun-0.3.3/lib/carrierwave-aliyun.rb:1:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/carrierwave-aliyun-0.3.3/lib/carrierwave-aliyun.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `block in require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.7.12/lib/bundler.rb:134:in `require'
	from /path/to/my/project/config/application.rb:7:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.2.0/lib/spring/application.rb:82:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.2.0/lib/spring/application.rb:82:in `preload'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.2.0/lib/spring/application.rb:143:in `serve'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.2.0/lib/spring/application.rb:131:in `block in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `loop'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.2.0/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

See this:
https://github.com/mailgun/mailgun-ruby/issues/15

**Comment by cheunghy** [comment]
Thanks, and this issue is resolved.
